# Generated by Django 3.2.3 on 2021-06-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
