# Generated by Django 3.2.3 on 2021-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createdata', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=45)),
                ('room_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('nickname', models.CharField(max_length=50)),
                ('cotent', models.TextField(blank=True)),
                ('room_title', models.CharField(max_length=45)),
                ('room_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=50)),
                ('login_check', models.BooleanField(default=False)),
            ],
        ),
    ]
