# Generated by Django 3.2.3 on 2021-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createdata', '0006_food_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=45)),
                ('room_id', models.CharField(max_length=45)),
            ],
        ),
    ]
